django_shop/auth_and_reg/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('password_reset/done/', PasswordResetUserDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', PasswordResetUserConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetUserCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/', PasswordResetUserView.as_view(), name='password_reset_form'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
]

django_shop/cart/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove-cabinet/(?P<product_id>\d+)/$', views.cart_remove_cabinet, name='cart_remove_cabinet'),
    re_path(r'^remove-cart/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_shop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),

]

urlpatterns += [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
]

urlpatterns += [
    path('user_cabinet/', include(('user_cabinet.urls', 'user_cabinet'), namespace='user_cabinet')),
]

urlpatterns += [
    path('auth_and_reg/', include(('auth_and_reg.urls', 'auth_and_reg'), namespace='auth_and_reg')),
]

urlpatterns += [
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/orders/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
]

django_shop/user_cabinet/urls.py
from django.urls import path, re_path, include
from . import views
from .views import *

urlpatterns = [
    path('', views.cabinet, name='cabinet'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('change_password', views.change_password, name='change_password'),
    path('change_password/change_pass_successful', views.change_password, name='change_pass_successful'),
    path('cart_profile', views.cart_profile, name='cart_profile'),
    path('history_orders', views.history_orders, name='history_orders'),
    path('history_orders/<int:order_id>/', views.detail_history_order, name='detail_history_order'),
]

django_shop/user_cabinet/forms.py
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django import forms


class ChangeUserForm(UserChangeForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='First name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(label='City', widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label='Address', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(label='Phone number', widget=forms.TextInput(attrs={'class': 'form-control'}))


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

django_shop/user_cabinet/views.py
import zoneinfo
import datetime
from django.contrib.auth.hashers import check_password
from django.core.paginator import Paginator
from django.http import HttpResponse
from user_cabinet.forms import ChangeUserForm, ChangePasswordForm
from django.shortcuts import render, get_object_or_404
from orders.models import OrderItem, Order


def cabinet(request):
    return render(request, 'cabinet/cabinet.html')


def cart_profile(request):
    return render(request, 'cabinet/cart_profile.html')


def edit_profile(request):
    if request.method == 'POST':
        t = datetime.datetime.now()
        current_user = request.user
        user_data = request.POST
        form = ChangeUserForm(user_data, instance=current_user)
        user_data._mutable = True
        user_data['username'] = current_user
        user_data['is_active'] = 'on'
        user_data['date_joined'] = datetime.datetime(t.year, t.month, t.day, t.hour, t.minute, t.second,
                                                     tzinfo=zoneinfo.ZoneInfo(key='UTC'))
        user_data._mutable = False
        print(user_data)
        if form.is_valid():
            form.save()
            return render(request, 'cabinet/user_data_change_successful.html')
        else:
            return HttpResponse('Error')
    else:
        form = ChangeUserForm(instance=request.user)
        return render(request, 'cabinet/edit_profile.html', {'form': form})


def change_password(request):
    current_user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            old_password = request.POST.get("old_password")
            if check_password(old_password, current_user.password):
                form.save()
                return render(request, 'cabinet/change_password_successful.html')
            else:
                return HttpResponse('Error')
    else:
        form = ChangePasswordForm(request.user)
    return render(request, 'cabinet/change_password.html', {'form': form, 'current_user': current_user})


def history_orders(request):
    orders = Order.objects.filter(email=request.user.email).values('id', 'created', 'paid')
    orders_item = OrderItem.objects.all()
    total_price = 0
    q_items = 0

    for i in orders:
        for o in orders_item:
            if i['id'] == o.order_id:
                total_price += o.price * o.quantity
                q_items += 1
        i.update({'total_price': total_price, 'q_items': q_items})
        q_items = 0
        total_price = 0

    paginator = Paginator(orders, 1)
    page_number = request.GET.get('page')
    pages = paginator.get_page(page_number)
    context = {'orders_item': orders_item, 'orders': orders, 'pages': pages}

    return render(request, 'cabinet/history_orders.html', context=context)


def detail_history_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    orders_item = OrderItem.objects.filter(order_id=order_id)
    for i in orders_item:
        i.__dict__.update({"total_price": i.price * i.quantity})

    context = {'order': order, 'orders_item': orders_item}
    return render(request, 'cabinet/detail_history_order.html', context)

django_shop/user_cabinet/templates/cabinet/cabinet.html
{% extends 'shop/base.html' %}
{% block cabinet %}


<div class="cab">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link cabinet_menu"  aria-current="page" href="{% url 'user_cabinet:history_orders' %}" >History</a>
    </li>
    <li class="nav-item">
      <a  class="nav-link cabinet_menu" href="{% url 'user_cabinet:edit_profile' %}">Edit profile</a>
    </li>
    <li class="nav-item">
      <a  class="nav-link cabinet_menu" href="{% url 'user_cabinet:change_password' %}">Change password</a>
    </li>
    <li class="nav-item">
      <a  class="nav-link cabinet_menu" href="{% url 'user_cabinet:cart_profile' %}" tabindex="-1" aria-disabled="true">Cart</a>
    </li>
  </ul>
</div>

{% endblock cabinet %}

django_shop/user_cabinet/templates/cabinet/cart_profile.html
{% include "cabinet/cabinet.html"  %}

<div class="profile_d">
    <H1>Cart</H1>
    <div style="margin-top: 40px;">
        <table class="table">
            <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Unit price</th>
                <th>Price</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ get_absolute_url }}">
                                <img src="{{ product.image.url }}" style="width: 100px;">
                            </a>
                        </td>
                        <td>{{ product.name }} </td>
                        <td>{{ item.quantity }} </td>
                        <td class="num">{{ item.price }} UAH </td>
                        <td class="num">{{ item.total_price }} UAH </td>
                        <td><a href="{% url 'cart:cart_remove_cabinet' product.id %}"> Remove </a></td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td><b>Total</b></td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }} UAH</td>
            </tr>
            </tbody>
        </table>
        <p class="text-right">
                <a href="{% url 'home' %}" class="button light">Continue shopping</a>
            {% if cart.get_total_price > 0 %}
                <a href="{% url 'orders:order_create' %}" class="button"> Checkout </a>
            {% endif %}
        </p>
    </div>
</div>

django_shop/user_cabinet/templates/cabinet/change_password.html
{% include "cabinet/cabinet.html"  %}
<head>
    <meta charset="UTF-8">
    <title>Change password</title>
</head>

<div class="container profile_d">
      <H1>Change password</H1>
      <form method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <p><input type="submit" value="Change password"></p>
      </form>
</div>

django_shop/user_cabinet/templates/cabinet/change_password_successful.html
{% include "cabinet/cabinet.html"  %}

<head>
    <meta charset="UTF-8">
    <title>Password has been changed</title>
</head>

<body>
    <div class="container profile_d">
        <H1>Password has been changed</H1>
        <a href="{% url 'auth_and_reg:login' %}">You must log in again</a>
    </div>
</body>

django_shop/user_cabinet/templates/cabinet/detail_history_order.html
{% include "cabinet/cabinet.html"  %}

<div class="profile_d">

<h1>Order № {{order.id}}</h1>
<table class="table">
    <thead>
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    </thead>

    {% for p in orders_item %}
    <tr>
        <td>{{p.product}}</td>
        <td>{{p.quantity}}</td>
        <td>{{p.total_price}} UAH</td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'user_cabinet:history_orders' %}"><input type="button" value="Back"/> </a>

</div>

django_shop/user_cabinet/templates/cabinet/edit_profile.html
{% include "cabinet/cabinet.html"  %}

<div class="profile_d">
    <H1>Edit profile</H1>
    <form method="post" class="order-form">
        {% csrf_token %}
        {{form.first_name.label}}
        {{form.first_name}}
        {{form.last_name.label}}
        {{form.last_name}}
        {{form.email.label}}
        {{form.email}}
        {{form.city.label}}
        {{form.city}}
        {{form.address.label}}
        {{form.address}}
        {{form.phone_number.label}}
        {{form.phone_number}}
        <br>
        <button type="submit">Change profile</button>
    </form>
</div>

django_shop/user_cabinet/templates/cabinet/history_orders.html
{% include "cabinet/cabinet.html"  %}

<div class="profile_d">
    <H1>History orders</H1>
<table class="table">
      <tbody>
    <thead>
        <tr>
            <th>Oreder</th>
            <th>Date</th>
            <th>Time</th>
            <th>Total price</th>
            <th></th>
        </tr>
    </thead>

    {% for p in pages %}
        <tr>
            <td scope="row"> № {{ p.id }} </td>
            <td scope="row"> {{ p.created|date:"d.m.Y" }}</td>
            <td scope="row"> {{ p.created|date:"h:m" }}</td>
            <td scope="row"> {{ p.total_price }} UAH</td>
            <td scope="row"> <a href="{% url 'user_cabinet:detail_history_order' p.id %}"><input type="button" value="Detail"/> </a> </td>
        </tr>
    {% endfor %}


      </tbody>
</table>

<!--Pagination-->
    <div class="pag_h">
        <nav aria-label="..." class="nav_h">
            <ul class="pagination">
                {% if pages.has_previous %}
                    <li class="page-item" >
                        <a class="page-link" href="?page=1" tabindex="-1">First</a>
                    </li>
                {% endif %}

                {% if pages.number == 1 %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">First</a>
                    </li>
                {% endif %}

                {% if pages.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                    </li>
                {% endif %}

                {% if pages.number == 1 %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                {% endif %}


                {% for p in pages.paginator.page_range %}
                    {% if pages.number == p %}
                        <li class="page-item active">
                           <a class="page-link" href="?page={{ p }}"> {{pages.number}} <span class="sr-only"> (current) </span></a>
                        </li>
                    {% elif p >= pages.number|add:-3 and p <= pages.number|add:3 %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}


                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ pages.next_page_number }} ">Next</a>
                    </li>
                {% endif %}

                {% if pages.number == pages.paginator.num_pages %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                {% endif %}

                {% if pages.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ pages.paginator.num_pages }}">Last</a>
                    </li>
                {% endif %}

                {% if pages.number == pages.paginator.num_pages %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

django_shop/user_cabinet/templates/cabinet/user_data_change_successful.html
{% extends 'shop/base.html' %}
{% block cabinet %}

<head>
    <meta charset="UTF-8">
    <title>Profile has been changed</title>
</head>
<body>
    <div class="container profile_d">
    <H1>Profile has been changed</H1>
    <a href="{% url 'user_cabinet:edit_profile' %}">Back to cabinet</a>
    </div>
</body>

{% endblock cabinet %}