django_shop/auth_and_reg/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('password_reset/done/', PasswordResetUserDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', PasswordResetUserConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetUserCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/', PasswordResetUserView.as_view(), name='password_reset_form'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
]

django_shop/cart/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove-cabinet/(?P<product_id>\d+)/$', views.cart_remove_cabinet, name='cart_remove_cabinet'),
    re_path(r'^remove-cart/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_shop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),

]

urlpatterns += [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
]

urlpatterns += [
    path('user_cabinet/', include(('user_cabinet.urls', 'user_cabinet'), namespace='user_cabinet')),
]

urlpatterns += [
    path('auth_and_reg/', include(('auth_and_reg.urls', 'auth_and_reg'), namespace='auth_and_reg')),
]

urlpatterns += [
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/auth_and_reg/models.py
from django.db import models

# Create your models here.

django_shop/auth_and_reg/forms.py
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, forms
from extension_users.models import User
from django.contrib.auth.hashers import check_password


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class PasswordResetFormUser(PasswordResetForm):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))


class CustomPasswordResetUserConfirmForm(SetPasswordForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='First name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(label='City', widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label='Address', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(label='Phone number', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = (
            'username', 'email', 'first_name', 'last_name', 'city', 'address', 'phone_number', 'password1', 'password2')


class CustomUserCreationForm(RegisterUserForm):

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email Already Exist")
        return email


class CustomUserLoginForm(LoginUserForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(_("Your account has expired. \Please click the renew subscription link below"),
                                        code='inactive', )

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        if User.objects.filter(username=username).exists():
            return username
        else:
            raise forms.ValidationError("This user doesn't exist")

    def clean_password(self):
        if 'username' in self.cleaned_data:
            username = self.cleaned_data['username'].lower()
            password = self.cleaned_data['password']
            user = User.objects.filter(username=username)
            if check_password(password, user[0].password):
                if not user[0].is_active:
                    raise forms.ValidationError(
                        ("Уour account has not been activated. We sent link to {} for activate your account".format(
                            user[0].email)),
                        code='inactive', )
                return password
            else:
                raise forms.ValidationError("Wrong password")


class CustomUserPasswordResetForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email does not exist")
        return email

django_shop/auth_and_reg/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from auth_and_reg.forms import CustomUserCreationForm, CustomUserLoginForm, CustomUserPasswordResetForm
from auth_and_reg.token import account_activation_token
from extension_users.models import User


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password2'])
            new_user.is_active = False
            new_user.save()
            send_activate_email(get_current_site(request), new_user)
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})


def send_activate_email(current_site, user):
    current_site = current_site
    mail_subject = 'Confirm registration'
    message = render_to_string('account_active_email.html', {
        'new_user': user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
    })
    to_email = user.email
    email = EmailMessage(subject=mail_subject, body=message, to=[to_email])
    email.send()


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_verify = True
        user.save()
        return render(request, 'account_active_email_done.html')
    else:
        return HttpResponse('Activation link is invalid!')


class LoginUser(LoginView):
    form_class = CustomUserLoginForm
    success_url = reverse_lazy('home')
    template_name = 'login.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        if 'data' in kwargs:
            form_user = kwargs['data']['username']
            if User.objects.filter(username=form_user).exists():
                user = User.objects.filter(username=form_user)
                if not user[0].is_active:
                    send_activate_email(get_current_site(self.request), user[0])
        return kwargs

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(requests):
    logout(requests)
    return redirect('home')


class PasswordResetUserView(PasswordResetView):
    form_class = CustomUserPasswordResetForm
    success_url = reverse_lazy('auth_and_reg:password_reset_done')
    email_template_name = 'password_reset_email.html',
    template_name = 'password_reset_form.html'


class PasswordResetUserConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('auth_and_reg:password_reset_complete')


class PasswordResetUserDoneView(PasswordResetDoneView):
    template_name = 'password_reset_done.html'


class PasswordResetUserCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'

django_shop/auth_and_reg/templates/account_active_email.html
{% autoescape off %} 
Hi {{ new_user.username }}, Please click on the link to confirm your registration,
http://{{ domain }}{% url 'auth_and_reg:activate' uidb64=uid token=token %}
{% endautoescape %}

django_shop/auth_and_reg/templates/account_active_email_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Thank you for your email confirmation. Now you can login your account.
<a class="nav-link navbar-brand" href="{% url 'auth_and_reg:login' %}">Login</a>
</body>
</html>

django_shop/auth_and_reg/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link type="text/css" href="{% static 'shop/css/styles.css' %}" rel = "stylesheet"/>
</head>
<body>

<div class="container">
    <h2>Login</h2>
     <br>
        <form method="post">
              {% csrf_token %}
              <div class="form_error" {{ form.non_field_errors }}</div>

              {% for f in form %}
              <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
              {{ f }}
              <div class="form-error">{{ f.errors }}</div>
              {% endfor %}
        </form>
        <br>
        <button type="submit" class="btn btn-primary">Login</button>
        <br><br>
        <a href="{% url 'home' %}">Back to Home</a> | <a href="{% url 'auth_and_reg:password_reset_form' %}">Reset password</a>
</div>
</body>
</html>

django_shop/auth_and_reg/templates/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Password reset complete</h1>
<p>Now, you can <a href="{% url 'auth_and_reg:login' %}">log in</a> with your new password </p>
</body>
</html>

django_shop/auth_and_reg/templates/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

  <H1>Password reset confirm</H1>
</head>
<body>
<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}

	  {% for field in form %}
		<p>{{ field.label_tag }}</p>
	        	{{ field }}
	        	<p>{% if field.errors %}</p>
	        		<small>{{ field.errors|striptags  }}</small>
	        	{% endif %}
		{% endfor %}


	  <div>
	    <p><button type="submit" class="btn btn-primary">Reset Password</button></p>
	  </div>
	</form>
</div>
</body>
</html>

django_shop/auth_and_reg/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
    <H1>Password reset done</H1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
</body>
</html>

django_shop/auth_and_reg/templates/password_reset_email.html
{% autoescape off %}

You're receiving this email because you requested a password reset for your user account at {{domain}}

Please click the following link to reset your password:

{{ protocol }}://{{ domain }}{% url "auth_and_reg:password_reset_confirm" uidb64=uid token=token %}

{% endautoescape %}

django_shop/auth_and_reg/templates/password_reset_form.html
<head>
    <meta charset="UTF-8">
    <title>Reset your password</title>
</head>
<body>
    <h1>Forgotten your password?</h1>
    <p>Enter your e-mail address to obtain a new password.</p>
    <form method="post">
        {{ form.as_p }}
        <p><input type="submit" value="Send e-mail"></p>
        {% csrf_token %}
    </form>
</body>

django_shop/auth_and_reg/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link type="text/css" href="{% static 'shop/css/styles.css' %}" rel = "stylesheet"/>
</head>
<body>


<div class="container">
    <h2>Register</h2>
    <br>
    <form method="post">
        {% csrf_token %}
            {% for f in form %}
                <div class="mb-3">
                <label for="{{ f.id_for_label }}" class="form-label">{{f.label}}</label>
                    {{f}}
                    {{f.errors}}
                </div>
            {% endfor %}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <br>
    <a href="{% url 'auth_and_reg:login' %}">Back to login</a> | <a href="{% url 'home' %}">Back to Home</a>
    <br><br><br>
</div>
</body>
</html>