django_shop/auth_and_reg/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('password_reset/done/', PasswordResetUserDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', PasswordResetUserConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetUserCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/', PasswordResetUserView.as_view(), name='password_reset_form'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
]

django_shop/cart/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove-cabinet/(?P<product_id>\d+)/$', views.cart_remove_cabinet, name='cart_remove_cabinet'),
    re_path(r'^remove-cart/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_shop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),

]

urlpatterns += [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
]

urlpatterns += [
    path('user_cabinet/', include(('user_cabinet.urls', 'user_cabinet'), namespace='user_cabinet')),
]

urlpatterns += [
    path('auth_and_reg/', include(('auth_and_reg.urls', 'auth_and_reg'), namespace='auth_and_reg')),
]

urlpatterns += [
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('', index, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('category/<slug:category_slug>/', index, name='category'),
    path('product_detail/<slug:product_slug>/', product_detail, name='detail_product'),
    path('search/', index, name='search_results'),
]

django_shop/user_cabinet/urls.py
from django.urls import path, re_path, include
from . import views
from .views import *

urlpatterns = [
    path('', views.cabinet, name='cabinet'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('change_password', views.change_password, name='change_password'),
    path('change_password/change_pass_successful', views.change_password, name='change_pass_successful'),
    path('cart_profile', views.cart_profile, name='cart_profile'),
    path('history_orders', views.history_orders, name='history_orders'),
    path('history_orders/<int:order_id>/', views.detail_history_order, name='detail_history_order'),
]

django_shop/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    vendor_code = models.IntegerField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='products_img/%Y/%m/%d')
    description = models.TextField(blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail_product', kwargs={'product_slug': self.slug})


class Contacts(models.Model):
    name = models.CharField(max_length=200, db_index=True, unique=True)
    data = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

django_shop/shop/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseNotFound
from .models import *
from cart.forms import CartAddProductForm


def index(request, category_slug=None):
    if 'category' in request.path:
        slug = get_object_or_404(Category, slug=category_slug).slug
    else:
        slug = None

    search_query = request.GET.get('search', '')
    orderby = request.GET.get('orderby', '')
    min_price = request.GET.get('min_input')
    max_price = request.GET.get('max_input')
    products = filters(search_query=search_query, orderby=orderby, min_price=min_price, max_price=max_price, slug=slug)

    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()

    context = {'page_obj': page_obj,
               'cart_product_form': cart_product_form,
               'search_result': len(products),
               }

    if min_price and max_price:
        context.update({'min_price': min_price,
                        'max_price': max_price,
                        'filter': '&min_input={}&max_input={}'.format(min_price, max_price)
                        })
    if orderby:
        context.update({'orderby': '&orderby={}'.format(orderby)})
    if search_query:
        context.update({'search': '&search={}'.format(search_query)})

    return render(request, 'shop/list_products.html', context=context)


def filters(search_query=None, orderby=None, min_price=None, max_price=None, slug=None):
    if min_price and max_price and orderby and slug:
        return Product.objects.filter(
            Q(category__slug=slug) & Q(price__gte=min_price) & Q(price__lte=max_price)).order_by(orderby)
    elif min_price and max_price and slug:
        return Product.objects.filter(
            Q(category__slug=slug) & Q(price__gte=min_price) & Q(price__lte=max_price))
    elif orderby and slug:
        return Product.objects.filter(category__slug=slug).order_by(orderby)
    elif slug:
        return Product.objects.filter(category__slug=slug)
    elif search_query:
        return Product.objects.filter(Q(name__iregex=search_query) | Q(price__icontains=search_query))
    elif min_price and max_price and orderby:
        return Product.objects.filter(Q(price__gte=min_price) & Q(price__lte=max_price)).order_by(orderby)
    elif min_price and max_price:
        return Product.objects.filter(Q(price__gte=min_price) & Q(price__lte=max_price))
    elif orderby:
        return Product.objects.all().order_by(orderby)
    else:
        return Product.objects.all()


def contacts(request):
    contact = Contacts.objects.all()
    context = {'contact': contact}
    return render(request, 'shop/contacts.html', context=context)


def pageNotFound(exception):
    return HttpResponseNotFound('<h1> Страница не найдена </h1>')


def product_detail(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, 'shop/product_detail.html', context=context)

django_shop/shop/templates/shop/base.html
{% load static %}
{% load shop_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link type="text/css" href="{% static 'shop/css/styles.css' %}" rel = "stylesheet"/>
</head>
<body>

<!--Main menu-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'contacts' %}">Contacts <span class="sr-only"></span></a>
    </ul>

    <form class="form-inline my-2 my-lg-0" action="{% url 'search_results' %}" method="get">
        <input class="form-control mr-sm-2" type="search" style="width: 400px;" placeholder="Search.." aria-label="Search" name="search">
        <button class="btn btn-outline-success my-4 my-sm-0 mr-5" type="submit" >Search</button>
    </form>

      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
      <a class="nav-link navbar-brand" href="{% url 'cart:cart_detail' %}">In cart: {{ total_items }} pcs, {{ cart.get_total_price}} UAH </a>
          {% else %}
                <a class="nav-link navbar-brand" href="{% url 'cart:cart_detail' %}">Cart</a>
          {% endif %}
      {% endwith %}


      {% if request.user.is_authenticated %}
      <a class="nav-link navbar-brand" href="{% url 'user_cabinet:history_orders' %}">Cabinet </a>
      <span class="nav-link navbar-brand">Hello, {{ user.username }} </span>
      <a class="nav-link navbar-brand" href="{% url 'auth_and_reg:logout' %}">Log out</a>
      {% else %}
    <a class="nav-link navbar-brand" href="{% url 'auth_and_reg:login' %}">Login</a><a class="nav-link navbar-brand" href="{% url 'auth_and_reg:register' %}">Register</a>
      {% endif %}
  </div>
</nav>



<!--Sidebar-->
<div class="sidenav w-20" >
    <h1>Category</h1>
    <li class="active_c"><a href="{% url 'home' %}"> All categories </a></li>

    {% show_category %}
</div>



<!--Main content-->
{% block content %}
{% endblock content %}

{% block detail %}
{% endblock detail %}

{% block contacts %}
{% endblock contacts %}

{% block cabinet %}
{% endblock cabinet %}

{% block search_result %}
{% endblock search_result %}


</body>

<!--Footer-->
<div class="footer">
    {% show_footer %}
</div>
</html>

django_shop/shop/templates/shop/contacts.html
{% extends 'shop/base.html' %}

{% block contacts %}

<div class="contacts_d">
<h1>Contacts</h1>
     <br><br>
    {% for c in contact%}
        <span><b>{{c.name}}</b>: {{c.data}}</span>
        <br><br>
    {% endfor %}
</div>

{% endblock contacts %}

django_shop/shop/templates/shop/footer.html
<div class="container">
    <div class="row">
        <div class="col-sm float-sm-left">
            {% for c in contacts%}
            <b>{{c.name}}</b>: {{c.data}}
            <br>
            {% endfor %}
        </div>
        <div class="col-sm">
        </div>
        <div class="col-sm float-left">
            @2023 Shop
        </div>
    </div>
</div>

django_shop/shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block content %}

<!--Content-->
<div class="w-80 content_m">

<!--Filters-->
{% if not search %}
<div class="filters">
    <form method="get" id="filterProduct">
        Filter by price: <input type="number" id="min_input" name="min_input" value="{{min_price}}"> - <input type="number" id="max_input" name="max_input" value="{{max_price}}">
        <button type="submit"><b>filter</b></button>
              <div class="dropdown sort">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <b>sort</b>
              </button>
                   <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <button type="submit" name="orderby" value="price" class="dropdown-item">price (lower first) </button>
                      <button type="submit" name="orderby" value="-price" class="dropdown-item">price (highest first) </button>
                      <button type="submit" name="orderby" value="name" class="dropdown-item">name (A-Z) </button>
                      <button type="submit" name="orderby" value="-name" class="dropdown-item">name (Z-A) </button>
                   </div>
              </div>
    </form>
</div>
{% endif%}

{% if search_result >= 0 and search %}
    <div class="search_f">
        <h1>Search found: {{search_result}} results </h1>
    </div>
{% endif%}

{% block list_products %}
{% endblock list_products %}
</div>


<!--Pagination-->
<div class="d_pagination">
    <nav aria-label="..." class="n_pagination">
        <ul class="pagination">

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{{search}}{{orderby}}{{filter}}" tabindex="-1">First</a>
                </li>
            {% endif %}

            {% if page_obj.number == 1 %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">First</a>
                </li>
            {% endif %}

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}{{search}}{{orderby}}{{filter}}" tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% if page_obj.number == 1 %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                    <li class="page-item active">
                       <a class="page-link" href="?page={{p}}{{search}}{{orderby}}{{filter}}"> {{page_obj.number}} <span class="sr-only"> (current) </span></a>
                    </li>
                {% elif p >= page_obj.number|add:-5 and p <= page_obj.number|add:5 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{p}}{{search}}{{orderby}}{{filter}}">{{ p }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}{{search}}{{orderby}}{{filter}}">Next</a>
                </li>
            {% endif %}

            {% if page_obj.number == page_obj.paginator.num_pages %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.paginator.num_pages}}{{search}}{{orderby}}{{filter}}">Last</a>
                </li>
            {% endif %}

            {% if page_obj.number == page_obj.paginator.num_pages %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Last</a>
                </li>
            {% endif %}

        </ul>
    </nav>
</div>

{% endblock content %}

django_shop/shop/templates/shop/list_category.html
{% for c in category %}
        <li class="active_c"><a href="{{ c.get_absolute_url }}" name="cat_url"> {{ c.name }} </a></li>
{% endfor %}

django_shop/shop/templates/shop/list_products.html
{% extends 'shop/index.html' %}

{% block list_products %}

{% for i in page_obj %}
        <div class="product-item" id="{{ i.category.name }}">
            <img src="{{ i.image.url }}">
            <div class="product-list">
                <h3>{{i.name}}</h3>
                <span class="price"> {{ i.price }} UAH</span>
                {% if i.available >= 10 %}
                    <form action="{% url 'cart:cart_add' product_id=i.id%}" method="post">
                        {% csrf_token %}
                        <span style="display: none;">{{cart_product_form}}</span>
                        <input type="submit" value="Add to cart" class="button sub_b">
                    </form>
                {% elif i.available == 0 %}
                <b>NOT AVAILABLE</b>
                {% elif i.available < 10 %}
                <span class="end_s"> Will end soon </span> <br>
                <form action="{% url 'cart:cart_add' i.id%}" method="post">
                        {% csrf_token %}
                        <span style="display: none;">{{cart_product_form}}</span>
                        <input type="submit" value="Add to cart" class="button add_c">
                    </form>
                {% endif %}
                <a href="{{ i.get_absolute_url }}" class="button">Detail</a>
            </div>
        </div>
{% endfor %}

{% endblock list_products %}

django_shop/shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block detail %}

<div class="det_m">
    <div class="card">
          <div class="card-body">
                <h4 class="card-title">{{product.name}}</h4>
                <br>
                <img class="card-img-bottom" src="{{product.image.url}}" alt="{{product.name}}">
          </div>
    </div>
 <div class="card_d">
       <p class="p_desc">{{product.description}}</p>
       <span class="p_l"><h3> Price {{product.price}} UAH </h3>
           {% if product.available %}
            <form action="{% url 'cart:cart_add' product.id%}" method="post">
                {% csrf_token %}
                {{cart_product_form}}
                <input type="submit" value="Add to cart">
            </form>
        </span>
       {% endif %}

</div>
</div>

{% endblock detail %}