django_shop/cart/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove-cabinet/(?P<product_id>\d+)/$', views.cart_remove_cabinet, name='cart_remove_cabinet'),
    re_path(r'^remove-cart/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_shop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),

]

urlpatterns += [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
]

urlpatterns += [
    path('user_cabinet/', include(('user_cabinet.urls', 'user_cabinet'), namespace='user_cabinet')),
]

urlpatterns += [
    path('auth_and_reg/', include(('auth_and_reg.urls', 'auth_and_reg'), namespace='auth_and_reg')),
]

urlpatterns += [
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/orders/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
]

django_shop/cart/models.py
from django.db import models

# Create your models here.

django_shop/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    quantity = forms.IntegerField(min_value=1, max_value=999, initial=1)

django_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove_cabinet(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('user_cabinet:cart_profile')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

django_shop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<div style="width: 1000px; float: left; margin-top: -850px; margin-left: 650px;">
    <h1>Your shopping cart</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit price</th>
            <th>Price</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ get_absolute_url }}">
                            <img src="{{ product.image.url }}" style="width: 100px;">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td class="num">{{ item.price }} UAH</td>
                    <td class="num">{{ item.total_price }} UAH</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td><b>Total</b></td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} UAH</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
            <a href="{% url 'home' %}" class="button light">Continue shopping</a>
        {% if cart.get_total_price > 0 %}
            <a href="{% url 'orders:order_create' %}" class="button"> Checkout </a>
        {% endif %}
    </p>
</div>

{% endblock %}